src/ProjetoKnockout/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoKnockout.Entities;
using ProjetoKnockout.Models;

namespace ProjetoKnockout.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Search()
        {
            using (DatabaseContext context = new DatabaseContext())
            {
                var query = context.Courses.ToList();
                var result = (from course in query
                                  select new
                            {
                                CourseID = course.CourseID,
                                CourseName = course.CourseName,
                                CompletionDate = course.CompletionDate.ToShortDateString()
                            }).ToList();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Pastable(IEnumerable<IEnumerable<PasteParameter>> Grid)
        {
            using (DatabaseContext context = new DatabaseContext())
            {
                foreach (var item in Grid)
                {
                    var course = new Course()
                    {
                        CourseName = item.FirstOrDefault(x => x.Name == "CourseName").Value,
                        CompletionDate = Convert.ToDateTime(item.FirstOrDefault(x => x.Name == "CompletionDate")),
                    };

                    context.Courses.Add(course);
                }
                context.SaveChanges();

                return Json(new { success = true, message = "" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult New()
        {
            //using (var context = new DatabaseContext())
            //{
                //var model = new CourseFormViewModel() { Context = context };
                //model.LoadDefaultValues();

                return View("Form");
            //}
        }


        [HttpPost]
        public ActionResult New(CourseFormViewModel model)
        {
            return Save(model);
        }

        private ActionResult Save(CourseFormViewModel model)
        {
            using (var context = new DatabaseContext())
            {
                model.Context = context;

                if (!ModelState.IsValid)
                {
                    model.LoadDefaultValues();
                    return View("Form", model);
                }

                var course = context.Courses.SingleOrDefault(c => c.CourseID == model.CourseID);
                if (course == null)
                {
                    course = new Course();
                    context.Courses.Add(course);
                }

                course.CourseName = model.CourseName;
                course.CompletionDate = model.CompletionDate;

                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        public ActionResult Edit(int id)
        {
            using (var context = new DatabaseContext())
            {
                var model = new CourseFormViewModel();
                model.Context = context;
                model.CourseID = id;

                //model.LoadDefaultValues();

                var course = context.Courses.SingleOrDefault(x => x.CourseID == id);

                if (course != null)
                {
                    model.CourseName = course.CourseName;
                    model.CompletionDate = course.CompletionDate;
                }

                return View("Form", model);
            }
        }

        [HttpPost]
        public ActionResult Edit(CourseFormViewModel model)
        {
            return Save(model);
        }


        public JsonResult Delete(int id)
        {
            using (var context = new DatabaseContext())
            {
                var course = context.Courses.SingleOrDefault(x => x.CourseID == id);

                if (course == null)
                {
                    return Json(new { success = false, message = "Course not found." }, JsonRequestBehavior.AllowGet);
                }

                context.Courses.Remove(course);

                context.SaveChanges();

                return Json(new { success = true, message = "" }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

src/ProjetoKnockout/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoKnockout.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /Dashboard/

        public ActionResult Index()
        {
            return View();
        }

    }
}

src/ProjetoKnockout/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoKnockout.Entities;
using ProjetoKnockout.Models;

namespace ProjetoKnockout.Controllers
{
    public class StudentController : Controller
    {
        //
        // GET: /Student/

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Search()
        {
            using (DatabaseContext context = new DatabaseContext())
            {
                var query = context.Students.ToList();
                var result = (from student in query
                              select new
                              {
                                  StudentId = student.StudentId,
                                  StudentName = student.StudentName,
                                  DateOfBirth = student.DateOfBirth.ToShortDateString(),
                                  Phone = student.Phone,
                                  Address = student.Address,
                                  CEP = student.CEP
                              }).ToList();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult New()
        {
            using (var context = new DatabaseContext())
            {
                var model = new StudentFormViewModel() { Context = context };
                model.LoadDefaultValues();

                return View("Form", model);
            }
        }
        [HttpPost]
        public ActionResult New(StudentFormViewModel model)
        {
            return Save(model);
        }

        private ActionResult Save(StudentFormViewModel model)
        {
            using (var context = new DatabaseContext())
            {
                model.Context = context;

                if (!ModelState.IsValid)
                {
                    model.LoadDefaultValues();
                    return View("Form", model);
                }

                var student = context.Students.SingleOrDefault(s => s.StudentId == model.StudentId);
                if (student == null)
                {
                    student = new Student();
                    context.Students.Add(student);
                }

                student.StudentName = model.StudentName;
                student.DateOfBirth = model.DateOfBirth;
                student.Phone = model.Phone;
                student.Address = model.Address;
                student.CEP = model.CEP;
                student.Courses = model.Courses;

                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        public ActionResult Edit(int id)
        {
            using (var context = new DatabaseContext())
            {
                var model = new StudentFormViewModel();
                model.Context = context;
                model.StudentId = id;

                model.LoadDefaultValues();

                var student = context.Students.SingleOrDefault(x => x.StudentId == id);

                if (student != null)
                {
                    model.StudentName = student.StudentName;
                    model.DateOfBirth = student.DateOfBirth;
                    model.Phone = student.Phone;
                    model.Address = student.Address;
                    model.CEP = student.CEP;
                    model.Courses = student.Courses;
                }

                return View("Form", model);
            }
        }

        [HttpPost]
        public ActionResult Edit(StudentFormViewModel model)
        {
            return Save(model);
        }


        public JsonResult Delete(int id)
        {
            using (var context = new DatabaseContext())
            {
                var student = context.Students.SingleOrDefault(x => x.StudentId == id);

                if (student == null)
                {
                    return Json(new { success = false, message = "Student not found." }, JsonRequestBehavior.AllowGet);
                }

                context.Students.Remove(student);

                context.SaveChanges();

                return Json(new { success = true, message = "" }, JsonRequestBehavior.AllowGet);
            }
        }


    }
}

src/ProjetoKnockout/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="">
    <meta name="author" content="">
    @Styles.Render("~/Bootstrap/css")
    @Styles.Render("~/jqueryui/css")
    @Styles.Render("~/Main/css")
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="@Url.Content("~/Assets/js/ie-emulation-modes-warning.js")"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="@Url.Content("~/Assets/js/ie10-viewport-bug-workaround.js")"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Project Knockout", "Index", "Dashboard", new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Search...">
                </form>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li class="active">@Html.ActionLink("Home", "Index", "Dashboard")</li>
                    <li>@Html.ActionLink("List of Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("New Student", "Form", "Student")</li>
                    <li>@Html.ActionLink("List of Courses", "Index", "Course")</li>
                    <li>@Html.ActionLink("New Course", "Form", "Course")</li>
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <ol class="breadcrumb">
                    <li><a href="#">@ViewBag.Controller</a></li>
                    <li class="active">@ViewBag.Title</li>
                </ol>
                @RenderBody()
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/Bootstrap/js")
    @Scripts.Render("~/Knockout/js")
    @RenderSection("scripts", required: false)
</body>
</html>